import { Geist, Geist_Mono,Inter,Noto_Sans_TC } from "next/font/google";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const notoSans = 

const noto_sans_tc = Noto_Sans_TC({ 
  subsets: ['latin','chinese-traditional'],  // 指定字體子集
  variable: "--font-noto_sans_tc",  // 指定 CSS 變數名稱
  // 可選配置
  // weight: ['400', '700'],  // 指定字重
  // display: 'swap',     // 字體顯示策略
})


const inter = Inter({ 
  subsets: ['latin','chinese-traditional'],  // 指定字體子集
  variable: "--font-inter",  // 指定 CSS 變數名稱
  // 可選配置
  // weight: ['400', '700'],  // 指定字重
  // display: 'swap',     // 字體顯示策略
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet" /> */}
      </head>
      <body
        className={` ${noto_sans_tc.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
